---
output: rmarkdown::github_document.
title: "How to install and use R-Studio"
author: "Kyla McConnell & Julia Mueller"
---

## If you're installing R for the first time

R is a programming language that can be written directly into your computer's console/terminal. However, almost all users of R pair it with the program R-Studio, an integrated development environment (IDE) that offers a ton of features that will make your life much easier! 

Download R here (if in Germany): https://ftp.gwdg.de/pub/misc/cran/
Or select a closer location ("mirror") here to optimize performance: https://ftp.gwdg.de/pub/misc/cran/

Then download R-Studio (Desktop) here: https://rstudio.com/products/rstudio/download/

More installation info here if you have trouble: https://rstudio-education.github.io/hopr/starting.html

Windows users -- you might be prompted to download a program called RTools to use the package panel in R Studio. You can do this directly from the RStudio/CRAN webpage here: https://cran.rstudio.com/bin/windows/Rtools/

Mac users -- a program called XQuartz is needed for viewing some plots. This might not come up as a problem for you until later, but to be safe, you can also go ahead and install it now: https://www.xquartz.org/

Note: You must install both R AND R-Studio in order to use R-Studio for the rest of this tutorial. 

## If you need to update R and R-Studio
If you want to update R, you can simply download the newest version using the link above. Note, however, that you will likely have to reinstall all packages. This is still worth doing every so often so that you don't get too far behind, because new packages might not work on old R versions (but old packages might not work on new R versions). 

You can also update R Studio by redownloading it with the link above.

If you're on Windows, you can also use the installr package, here is some more info: https://www.r-statistics.com/2013/03/updating-r-from-r-on-windows-using-the-installr-package/

For Mac users, the 

## About R-Studio
